### ISSUE TITLE
which container to use?

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2018-container-lab#12]
A couple of our builds use `FROM registry.access.redhat.com/rhel7:7.4-129`. Do we want to update this?

**Comment by tchughesiv** [comment]
yes... whatever latest release is and we'll cache it pre-lab

**Comment by tchughesiv** [comment]
resolved by https://github.com/dustymabe/summit-2018-container-lab/pull/18

**Comment by dustymabe** [comment]
fixed
