### ISSUE TITLE
issue in lab5 instantiating template: registry not allowed by whitelist

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2018-container-lab#14]
for https://github.com/dustymabe/summit-2018-container-lab/blob/master/labs/lab5/chapter5.md#wordpress-templated-deployment 

```
-> Creating resources ...
    error: ImageStream "mariadb" is invalid: spec.tags[latest].from.name: Forbidden: registry "localhost:5000" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443",
 and 5 more ...
    error: ImageStream "wordpress" is invalid: spec.tags[latest].from.name: Forbidden: registry "localhost:5000" not allowed by whitelist: "172.30.1.1:5000", "docker.io:443", "*.docker.io:443", "*.redhat.com:443
", and 5 more ...
```

**Comment by dustymabe** [comment]
we basically need to get localhost into the whitelist and verify that works.

**Comment by tchughesiv** [comment]
fixed w/ https://github.com/dustymabe/summit-2018-container-lab/pull/18

**Comment by dustymabe** [comment]
for this one did you have to modify the `~/start_oc.sh` script?

**Comment by tchughesiv** [comment]
Nah... didn’t see any option for whitelist so instead modified ch 5 template to get away from image streams... pull from DC direct instead
