### ISSUE TITLE
using docker-latest

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2018-container-lab#2]
We are using docker-latest right now in our latest AMI. This causes problems for example [where we tell the user to inspect docker.service](https://github.com/dustymabe/summit-2018-container-lab/blob/master/labs/lab1/chapter1.md#docker-and-systemd).

If we move to cri-o then maybe this is a moot point. If not we'll need to go through and clean up a few things.

**Comment by dustymabe** [comment]
we could possibly install both docker and docker-latest and then copy the docker-latest binary over the docker binary to get around the issues

**Comment by scollier** [comment]
@dustymabe for this one, couldn't we just update the docs, rather than change the AMI?

**Comment by dustymabe** [comment]
I would prefer to not update it in the docs because while `s/docker/docker-latest` is easy I think it detracts from the learning and also requires us to explain what `docker-latest` is vs `docker` and I also think `docker-latest` is going away.

**Comment by scollier** [comment]
ok, i took a look at it @dustymabe. I don't think we have to copy over any binaries.  just installing docker seems to get past that point in the lab.  I'll create a new ami so you can confirm.

**Comment by dustymabe** [comment]
> ok, i took a look at it @dustymabe. I don't think we have to copy over any binaries. just installing docker seems to get past that point in the lab. I'll create a new ami so you can confirm.

nice. i thought we *needed* docker-latest for some reason. good to know that's not needed!
