### ISSUE TITLE
install podman in AMI

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2018-container-lab#20]
if we are going to use podman then we should install it in the AMI

**Comment by dustymabe** [comment]
also include buildah

**Comment by tchughesiv** [comment]
Already added them to ami playbook

**Comment by dustymabe** [comment]
> Already added them to ami playbook

does that exist somewhere? I'll try to look there first before I open new issues.

**Comment by dustymabe** [comment]
also we need to be careful. when i installed buildah I got an older version that didn't include the secrets patch we needed. maybe the yum metadata in this AMI I'm using is out of date.

**Comment by tchughesiv** [comment]
https://github.com/scollier/ansible-ami-builder/pull/13

Unless that code has changed since then

**Comment by scollier** [comment]
done
