### ISSUE TITLE
`RUN yum-config-manager --disable \* &> /dev/null` takes a long time

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2018-container-lab#21]
From: https://github.com/dustymabe/summit-2018-container-lab/blob/29d950aa4803bee43c34bbc7b39e320e5434680a/labs/lab2/bigapp/Dockerfile#L9

we need to make these systems not be registered to so many subscriptions

**Comment by scollier** [comment]
does someone have an account that reduces the number of subs?  some non-employee subscription account?
