### ISSUE TITLE
link doesn't appear

### ISSUE THREAD

**Issue by whitel** [dustymabe/summit-2018-container-lab#38]
"Give the deployment a minute or so to finish, and in the upper right hand side, you will see a new URL that points to your application. Click on that and it will open a new tab."

https://github.com/dustymabe/summit-2018-container-lab/blob/master/labs/lab6/chapter6.md#deploy-an-ansible-playbook-bundle-application

When the app is deployed i don't see a link at the top right. I just see it if i open the "deployment config" and then it is at the bottom right. Am I missing something? on the wrong page?

**Comment by tchughesiv** [comment]
could be related to newer ocp version... will take a look

**Comment by tchughesiv** [comment]
weird... i'm seeing the hello-world url just fine on the `Overview` page.
Maybe try again w/ my latest mods?
https://github.com/dustymabe/summit-2018-container-lab/pull/43
