### ISSUE TITLE
select project dropdown doesn't exist

### ISSUE THREAD

**Issue by whitel** [dustymabe/summit-2018-container-lab#39]
here: https://github.com/dustymabe/summit-2018-container-lab/blob/master/labs/lab6/chapter6.md#create-database

"Select apb project in the drop-down." 

^^ i don't get prompted for this. Is it because further up it said to be in the project already?

**Comment by whitel** [comment]
I am also prompted for a password w/o instructions for what password to use

**Comment by tchughesiv** [comment]
could be related to newer ocp version... will take a look
