### ISSUE TITLE
docker doesn't need sudo but podman does

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2018-container-lab#46]
in chapter 0 we run a few docker commands without sudo, but all of our podman commands need sudo. I suspect the AMI is set up to open up permissions on the docker socket. I think we should make docker require sudo too.

**Comment by tchughesiv** [comment]
@dustymabe we have the ability to run docker w/o sudo by adding our ec2-user to the docker group.
https://docs.docker.com/install/linux/linux-postinstall/

https://github.com/scollier/ansible-ami-builder/blob/8ac6aabbf8a65b9c4041924e171ed1a809c03c68/roles/ami_config/tasks/profiles/rh-container-lab.yml#L8-L12

**Comment by dustymabe** [comment]
> @dustymabe we have the ability to run docker w/o sudo by adding our ec2-user to the docker group.

yes, I'm saying let's not do that for our AMI

can you join IRC?

**Comment by tchughesiv** [comment]
Oh i see, misread it.

**Comment by dustymabe** [comment]
well we can at least make it `sudo docker` in the manual even if it isn't required.
